### ISSUE TITLE
controller not found

### ISSUE THREAD

**Issue by BlueHamster** [ReySi/Wizz#22]
when you are on the second step and you try to cancel the wizard, then you get a controller not found exception...

**Comment by ReySi** [comment]
do you want to return to the dashboard afterwards?
the controller is normally an attribute in the associated fxml, however that doesn't apply on the dashboard fxml.
maybe we should add this attribute.

**Comment by BlueHamster** [comment]
we said, that on cancel the application will return to dashboard?!
Or am I wrong?

**Comment by ReySi** [comment]
no i think so too.
try to add the line
fxmlLoader.setController(new DashboardController());
above
BorderPane root = (fxmlLoader.load(getClass().getResource("views/dashboard/dashboard.fxml").openStream()));

**Comment by BlueHamster** [comment]
sauber läuft

**Comment by BlueHamster** [comment]
ähm, ... it is working :)
